# Generated by Django 5.0.7 on 2024-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_sessao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
